/* IS_AUTOGENERATED_SO_ALLOW_AUTODELETE=YES */
/* The previous line is to allow auto deletion */

#import <Foundation/Foundation.h>
#import <Foundation/NSString.h>
#import "libGolgi.h"


@interface PinSetting : NSObject
{
    NSInteger pin;
    BOOL pinIsSet;
    NSInteger val;
    BOOL valIsSet;
    NSString *str;
    BOOL strIsSet;
}

@property (readonly) BOOL pinIsSet;
- (NSInteger)getPin;
- (void)setPin:(NSInteger )pin;
@property (readonly) BOOL valIsSet;
- (NSInteger)getVal;
- (void)setVal:(NSInteger )val;
@property (readonly) BOOL strIsSet;
- (NSString *)getStr;
- (void)setStr:(NSString *)str;

+ (PinSetting *)deserialiseFromString: (NSString *)string;
+ (PinSetting *)deserialiseFromPayload: (GolgiPayload *)payload;
- (NSString *)serialiseWithPrefix:(NSString *)prefix;
- (NSString *)serialise;
+ (PinSetting *)fromJSONObject:(GolgiJSONObject *)jsonObject;
+ (PinSetting *)fromJSONString:(NSString *)jsonString;
+ (PinSetting *)fromJSONObject:(GolgiJSONObject *)jsonObject error:(GolgiJSONError **)err;
+ (PinSetting *)fromJSONString:(NSString *)jsonString error:(GolgiJSONError **)err;
- (NSString *)toJSON;
- (id)initWithIsSet:(BOOL)defIsSet;
@end

@interface setPinArg : NSObject
{
    PinSetting *pinSetting;
    BOOL pinSettingIsSet;
}

@property (readonly) BOOL pinSettingIsSet;
- (PinSetting *)getPinSetting;
- (void)setPinSetting:(PinSetting *)pinSetting;

+ (setPinArg *)deserialiseFromString: (NSString *)string;
+ (setPinArg *)deserialiseFromPayload: (GolgiPayload *)payload;
- (NSString *)serialiseWithPrefix:(NSString *)prefix;
- (NSString *)serialise;
+ (setPinArg *)fromJSONObject:(GolgiJSONObject *)jsonObject;
+ (setPinArg *)fromJSONString:(NSString *)jsonString;
+ (setPinArg *)fromJSONObject:(GolgiJSONObject *)jsonObject error:(GolgiJSONError **)err;
+ (setPinArg *)fromJSONString:(NSString *)jsonString error:(GolgiJSONError **)err;
- (NSString *)toJSON;
- (id)initWithIsSet:(BOOL)defIsSet;
@end

@interface IOState : NSObject
{
    NSInteger ledState;
    BOOL ledStateIsSet;
}

@property (readonly) BOOL ledStateIsSet;
- (NSInteger)getLedState;
- (void)setLedState:(NSInteger )ledState;

+ (IOState *)deserialiseFromString: (NSString *)string;
+ (IOState *)deserialiseFromPayload: (GolgiPayload *)payload;
- (NSString *)serialiseWithPrefix:(NSString *)prefix;
- (NSString *)serialise;
+ (IOState *)fromJSONObject:(GolgiJSONObject *)jsonObject;
+ (IOState *)fromJSONString:(NSString *)jsonString;
+ (IOState *)fromJSONObject:(GolgiJSONObject *)jsonObject error:(GolgiJSONError **)err;
+ (IOState *)fromJSONString:(NSString *)jsonString error:(GolgiJSONError **)err;
- (NSString *)toJSON;
- (id)initWithIsSet:(BOOL)defIsSet;
@end

@interface PotValue : NSObject
{
    NSInteger v;
    BOOL vIsSet;
}

@property (readonly) BOOL vIsSet;
- (NSInteger)getV;
- (void)setV:(NSInteger )v;

+ (PotValue *)deserialiseFromString: (NSString *)string;
+ (PotValue *)deserialiseFromPayload: (GolgiPayload *)payload;
- (NSString *)serialiseWithPrefix:(NSString *)prefix;
- (NSString *)serialise;
+ (PotValue *)fromJSONObject:(GolgiJSONObject *)jsonObject;
+ (PotValue *)fromJSONString:(NSString *)jsonString;
+ (PotValue *)fromJSONObject:(GolgiJSONObject *)jsonObject error:(GolgiJSONError **)err;
+ (PotValue *)fromJSONString:(NSString *)jsonString error:(GolgiJSONError **)err;
- (NSString *)toJSON;
- (id)initWithIsSet:(BOOL)defIsSet;
@end

@interface GolDuino_setPin_reqArg : NSObject
{
    PinSetting *setting;
    BOOL settingIsSet;
}

@property (readonly) BOOL settingIsSet;
- (PinSetting *)getSetting;
- (void)setSetting:(PinSetting *)setting;

+ (GolDuino_setPin_reqArg *)deserialiseFromString: (NSString *)string;
+ (GolDuino_setPin_reqArg *)deserialiseFromPayload: (GolgiPayload *)payload;
- (NSString *)serialiseWithPrefix:(NSString *)prefix;
- (NSString *)serialise;
+ (GolDuino_setPin_reqArg *)fromJSONObject:(GolgiJSONObject *)jsonObject;
+ (GolDuino_setPin_reqArg *)fromJSONString:(NSString *)jsonString;
+ (GolDuino_setPin_reqArg *)fromJSONObject:(GolgiJSONObject *)jsonObject error:(GolgiJSONError **)err;
+ (GolDuino_setPin_reqArg *)fromJSONString:(NSString *)jsonString error:(GolgiJSONError **)err;
- (NSString *)toJSON;
- (id)initWithIsSet:(BOOL)defIsSet;
@end

@interface GolDuino_setPin_rspArg : NSObject
{
    NSInteger internalSuccess_;
    BOOL internalSuccess_IsSet;
    PinSetting *result;
    BOOL resultIsSet;
    GolgiException *golgiException;
    BOOL golgiExceptionIsSet;
}

@property (readonly) BOOL internalSuccess_IsSet;
- (NSInteger)getInternalSuccess_;
- (void)setInternalSuccess_:(NSInteger )internalSuccess_;
@property (readonly) BOOL resultIsSet;
- (PinSetting *)getResult;
- (void)setResult:(PinSetting *)result;
@property (readonly) BOOL golgiExceptionIsSet;
- (GolgiException *)getGolgiException;
- (void)setGolgiException:(GolgiException *)golgiException;

+ (GolDuino_setPin_rspArg *)deserialiseFromString: (NSString *)string;
+ (GolDuino_setPin_rspArg *)deserialiseFromPayload: (GolgiPayload *)payload;
- (NSString *)serialiseWithPrefix:(NSString *)prefix;
- (NSString *)serialise;
+ (GolDuino_setPin_rspArg *)fromJSONObject:(GolgiJSONObject *)jsonObject;
+ (GolDuino_setPin_rspArg *)fromJSONString:(NSString *)jsonString;
+ (GolDuino_setPin_rspArg *)fromJSONObject:(GolgiJSONObject *)jsonObject error:(GolgiJSONError **)err;
+ (GolDuino_setPin_rspArg *)fromJSONString:(NSString *)jsonString error:(GolgiJSONError **)err;
- (NSString *)toJSON;
- (id)initWithIsSet:(BOOL)defIsSet;
@end

@interface GolDuino_setIO_reqArg : NSObject
{
    IOState *ioState;
    BOOL ioStateIsSet;
}

@property (readonly) BOOL ioStateIsSet;
- (IOState *)getIoState;
- (void)setIoState:(IOState *)ioState;

+ (GolDuino_setIO_reqArg *)deserialiseFromString: (NSString *)string;
+ (GolDuino_setIO_reqArg *)deserialiseFromPayload: (GolgiPayload *)payload;
- (NSString *)serialiseWithPrefix:(NSString *)prefix;
- (NSString *)serialise;
+ (GolDuino_setIO_reqArg *)fromJSONObject:(GolgiJSONObject *)jsonObject;
+ (GolDuino_setIO_reqArg *)fromJSONString:(NSString *)jsonString;
+ (GolDuino_setIO_reqArg *)fromJSONObject:(GolgiJSONObject *)jsonObject error:(GolgiJSONError **)err;
+ (GolDuino_setIO_reqArg *)fromJSONString:(NSString *)jsonString error:(GolgiJSONError **)err;
- (NSString *)toJSON;
- (id)initWithIsSet:(BOOL)defIsSet;
@end

@interface GolDuino_setIO_rspArg : NSObject
{
    NSInteger internalSuccess_;
    BOOL internalSuccess_IsSet;
    GolgiException *golgiException;
    BOOL golgiExceptionIsSet;
}

@property (readonly) BOOL internalSuccess_IsSet;
- (NSInteger)getInternalSuccess_;
- (void)setInternalSuccess_:(NSInteger )internalSuccess_;
@property (readonly) BOOL golgiExceptionIsSet;
- (GolgiException *)getGolgiException;
- (void)setGolgiException:(GolgiException *)golgiException;

+ (GolDuino_setIO_rspArg *)deserialiseFromString: (NSString *)string;
+ (GolDuino_setIO_rspArg *)deserialiseFromPayload: (GolgiPayload *)payload;
- (NSString *)serialiseWithPrefix:(NSString *)prefix;
- (NSString *)serialise;
+ (GolDuino_setIO_rspArg *)fromJSONObject:(GolgiJSONObject *)jsonObject;
+ (GolDuino_setIO_rspArg *)fromJSONString:(NSString *)jsonString;
+ (GolDuino_setIO_rspArg *)fromJSONObject:(GolgiJSONObject *)jsonObject error:(GolgiJSONError **)err;
+ (GolDuino_setIO_rspArg *)fromJSONString:(NSString *)jsonString error:(GolgiJSONError **)err;
- (NSString *)toJSON;
- (id)initWithIsSet:(BOOL)defIsSet;
@end

@interface GolDuino_buttonPressed_reqArg : NSObject
{
    NSInteger t;
    BOOL tIsSet;
}

@property (readonly) BOOL tIsSet;
- (NSInteger)getT;
- (void)setT:(NSInteger )t;

+ (GolDuino_buttonPressed_reqArg *)deserialiseFromString: (NSString *)string;
+ (GolDuino_buttonPressed_reqArg *)deserialiseFromPayload: (GolgiPayload *)payload;
- (NSString *)serialiseWithPrefix:(NSString *)prefix;
- (NSString *)serialise;
+ (GolDuino_buttonPressed_reqArg *)fromJSONObject:(GolgiJSONObject *)jsonObject;
+ (GolDuino_buttonPressed_reqArg *)fromJSONString:(NSString *)jsonString;
+ (GolDuino_buttonPressed_reqArg *)fromJSONObject:(GolgiJSONObject *)jsonObject error:(GolgiJSONError **)err;
+ (GolDuino_buttonPressed_reqArg *)fromJSONString:(NSString *)jsonString error:(GolgiJSONError **)err;
- (NSString *)toJSON;
- (id)initWithIsSet:(BOOL)defIsSet;
@end

@interface GolDuino_buttonPressed_rspArg : NSObject
{
    NSInteger internalSuccess_;
    BOOL internalSuccess_IsSet;
    GolgiException *golgiException;
    BOOL golgiExceptionIsSet;
}

@property (readonly) BOOL internalSuccess_IsSet;
- (NSInteger)getInternalSuccess_;
- (void)setInternalSuccess_:(NSInteger )internalSuccess_;
@property (readonly) BOOL golgiExceptionIsSet;
- (GolgiException *)getGolgiException;
- (void)setGolgiException:(GolgiException *)golgiException;

+ (GolDuino_buttonPressed_rspArg *)deserialiseFromString: (NSString *)string;
+ (GolDuino_buttonPressed_rspArg *)deserialiseFromPayload: (GolgiPayload *)payload;
- (NSString *)serialiseWithPrefix:(NSString *)prefix;
- (NSString *)serialise;
+ (GolDuino_buttonPressed_rspArg *)fromJSONObject:(GolgiJSONObject *)jsonObject;
+ (GolDuino_buttonPressed_rspArg *)fromJSONString:(NSString *)jsonString;
+ (GolDuino_buttonPressed_rspArg *)fromJSONObject:(GolgiJSONObject *)jsonObject error:(GolgiJSONError **)err;
+ (GolDuino_buttonPressed_rspArg *)fromJSONString:(NSString *)jsonString error:(GolgiJSONError **)err;
- (NSString *)toJSON;
- (id)initWithIsSet:(BOOL)defIsSet;
@end

@interface GolDuino_buttonReleased_reqArg : NSObject
{
    NSInteger t;
    BOOL tIsSet;
}

@property (readonly) BOOL tIsSet;
- (NSInteger)getT;
- (void)setT:(NSInteger )t;

+ (GolDuino_buttonReleased_reqArg *)deserialiseFromString: (NSString *)string;
+ (GolDuino_buttonReleased_reqArg *)deserialiseFromPayload: (GolgiPayload *)payload;
- (NSString *)serialiseWithPrefix:(NSString *)prefix;
- (NSString *)serialise;
+ (GolDuino_buttonReleased_reqArg *)fromJSONObject:(GolgiJSONObject *)jsonObject;
+ (GolDuino_buttonReleased_reqArg *)fromJSONString:(NSString *)jsonString;
+ (GolDuino_buttonReleased_reqArg *)fromJSONObject:(GolgiJSONObject *)jsonObject error:(GolgiJSONError **)err;
+ (GolDuino_buttonReleased_reqArg *)fromJSONString:(NSString *)jsonString error:(GolgiJSONError **)err;
- (NSString *)toJSON;
- (id)initWithIsSet:(BOOL)defIsSet;
@end

@interface GolDuino_buttonReleased_rspArg : NSObject
{
    NSInteger internalSuccess_;
    BOOL internalSuccess_IsSet;
    GolgiException *golgiException;
    BOOL golgiExceptionIsSet;
}

@property (readonly) BOOL internalSuccess_IsSet;
- (NSInteger)getInternalSuccess_;
- (void)setInternalSuccess_:(NSInteger )internalSuccess_;
@property (readonly) BOOL golgiExceptionIsSet;
- (GolgiException *)getGolgiException;
- (void)setGolgiException:(GolgiException *)golgiException;

+ (GolDuino_buttonReleased_rspArg *)deserialiseFromString: (NSString *)string;
+ (GolDuino_buttonReleased_rspArg *)deserialiseFromPayload: (GolgiPayload *)payload;
- (NSString *)serialiseWithPrefix:(NSString *)prefix;
- (NSString *)serialise;
+ (GolDuino_buttonReleased_rspArg *)fromJSONObject:(GolgiJSONObject *)jsonObject;
+ (GolDuino_buttonReleased_rspArg *)fromJSONString:(NSString *)jsonString;
+ (GolDuino_buttonReleased_rspArg *)fromJSONObject:(GolgiJSONObject *)jsonObject error:(GolgiJSONError **)err;
+ (GolDuino_buttonReleased_rspArg *)fromJSONString:(NSString *)jsonString error:(GolgiJSONError **)err;
- (NSString *)toJSON;
- (id)initWithIsSet:(BOOL)defIsSet;
@end

@interface GolDuino_setPotValue_reqArg : NSObject
{
    NSInteger v;
    BOOL vIsSet;
}

@property (readonly) BOOL vIsSet;
- (NSInteger)getV;
- (void)setV:(NSInteger )v;

+ (GolDuino_setPotValue_reqArg *)deserialiseFromString: (NSString *)string;
+ (GolDuino_setPotValue_reqArg *)deserialiseFromPayload: (GolgiPayload *)payload;
- (NSString *)serialiseWithPrefix:(NSString *)prefix;
- (NSString *)serialise;
+ (GolDuino_setPotValue_reqArg *)fromJSONObject:(GolgiJSONObject *)jsonObject;
+ (GolDuino_setPotValue_reqArg *)fromJSONString:(NSString *)jsonString;
+ (GolDuino_setPotValue_reqArg *)fromJSONObject:(GolgiJSONObject *)jsonObject error:(GolgiJSONError **)err;
+ (GolDuino_setPotValue_reqArg *)fromJSONString:(NSString *)jsonString error:(GolgiJSONError **)err;
- (NSString *)toJSON;
- (id)initWithIsSet:(BOOL)defIsSet;
@end

@interface GolDuino_setPotValue_rspArg : NSObject
{
    NSInteger internalSuccess_;
    BOOL internalSuccess_IsSet;
    GolgiException *golgiException;
    BOOL golgiExceptionIsSet;
}

@property (readonly) BOOL internalSuccess_IsSet;
- (NSInteger)getInternalSuccess_;
- (void)setInternalSuccess_:(NSInteger )internalSuccess_;
@property (readonly) BOOL golgiExceptionIsSet;
- (GolgiException *)getGolgiException;
- (void)setGolgiException:(GolgiException *)golgiException;

+ (GolDuino_setPotValue_rspArg *)deserialiseFromString: (NSString *)string;
+ (GolDuino_setPotValue_rspArg *)deserialiseFromPayload: (GolgiPayload *)payload;
- (NSString *)serialiseWithPrefix:(NSString *)prefix;
- (NSString *)serialise;
+ (GolDuino_setPotValue_rspArg *)fromJSONObject:(GolgiJSONObject *)jsonObject;
+ (GolDuino_setPotValue_rspArg *)fromJSONString:(NSString *)jsonString;
+ (GolDuino_setPotValue_rspArg *)fromJSONObject:(GolgiJSONObject *)jsonObject error:(GolgiJSONError **)err;
+ (GolDuino_setPotValue_rspArg *)fromJSONString:(NSString *)jsonString error:(GolgiJSONError **)err;
- (NSString *)toJSON;
- (id)initWithIsSet:(BOOL)defIsSet;
@end

@interface GolDuino_getPotValue_reqArg : NSObject
{
    NSInteger pooky;
    BOOL pookyIsSet;
}

@property (readonly) BOOL pookyIsSet;
- (NSInteger)getPooky;
- (void)setPooky:(NSInteger )pooky;

+ (GolDuino_getPotValue_reqArg *)deserialiseFromString: (NSString *)string;
+ (GolDuino_getPotValue_reqArg *)deserialiseFromPayload: (GolgiPayload *)payload;
- (NSString *)serialiseWithPrefix:(NSString *)prefix;
- (NSString *)serialise;
+ (GolDuino_getPotValue_reqArg *)fromJSONObject:(GolgiJSONObject *)jsonObject;
+ (GolDuino_getPotValue_reqArg *)fromJSONString:(NSString *)jsonString;
+ (GolDuino_getPotValue_reqArg *)fromJSONObject:(GolgiJSONObject *)jsonObject error:(GolgiJSONError **)err;
+ (GolDuino_getPotValue_reqArg *)fromJSONString:(NSString *)jsonString error:(GolgiJSONError **)err;
- (NSString *)toJSON;
- (id)initWithIsSet:(BOOL)defIsSet;
@end

@interface GolDuino_getPotValue_rspArg : NSObject
{
    NSInteger internalSuccess_;
    BOOL internalSuccess_IsSet;
    PotValue *result;
    BOOL resultIsSet;
    GolgiException *golgiException;
    BOOL golgiExceptionIsSet;
}

@property (readonly) BOOL internalSuccess_IsSet;
- (NSInteger)getInternalSuccess_;
- (void)setInternalSuccess_:(NSInteger )internalSuccess_;
@property (readonly) BOOL resultIsSet;
- (PotValue *)getResult;
- (void)setResult:(PotValue *)result;
@property (readonly) BOOL golgiExceptionIsSet;
- (GolgiException *)getGolgiException;
- (void)setGolgiException:(GolgiException *)golgiException;

+ (GolDuino_getPotValue_rspArg *)deserialiseFromString: (NSString *)string;
+ (GolDuino_getPotValue_rspArg *)deserialiseFromPayload: (GolgiPayload *)payload;
- (NSString *)serialiseWithPrefix:(NSString *)prefix;
- (NSString *)serialise;
+ (GolDuino_getPotValue_rspArg *)fromJSONObject:(GolgiJSONObject *)jsonObject;
+ (GolDuino_getPotValue_rspArg *)fromJSONString:(NSString *)jsonString;
+ (GolDuino_getPotValue_rspArg *)fromJSONObject:(GolgiJSONObject *)jsonObject error:(GolgiJSONError **)err;
+ (GolDuino_getPotValue_rspArg *)fromJSONString:(NSString *)jsonString error:(GolgiJSONError **)err;
- (NSString *)toJSON;
- (id)initWithIsSet:(BOOL)defIsSet;
@end
//
// setPin
//
@protocol GolDuinoSetPinResultSender
- (NSString *)getRequestSenderId;
- (void)successWithResult:(PinSetting *)result;
@end
@protocol GolDuinoSetPinResultReceiver
- (void)successWithResult:(PinSetting *)result;
- (void)failureWithGolgiException:(GolgiException *)golgiException;
@end
@protocol GolDuinoSetPinRequestReceiver
- (void)setPinWithResultSender:(id<GolDuinoSetPinResultSender>)resultSender andSetting:(PinSetting *)setting;
@end
@interface GolDuinoSetPinExceptionBundle: NSObject
{
    GolgiException * golgiException;
}
@property GolgiException * golgiException;
@end

//
// setIO
//
@protocol GolDuinoSetIOResultSender
- (NSString *)getRequestSenderId;
- (void)success;
@end
@protocol GolDuinoSetIOResultReceiver
- (void)success;
- (void)failureWithGolgiException:(GolgiException *)golgiException;
@end
@protocol GolDuinoSetIORequestReceiver
- (void)setIOWithResultSender:(id<GolDuinoSetIOResultSender>)resultSender andIoState:(IOState *)ioState;
@end
@interface GolDuinoSetIOExceptionBundle: NSObject
{
    GolgiException * golgiException;
}
@property GolgiException * golgiException;
@end

//
// buttonPressed
//
@protocol GolDuinoButtonPressedResultSender
- (NSString *)getRequestSenderId;
- (void)success;
@end
@protocol GolDuinoButtonPressedResultReceiver
- (void)success;
- (void)failureWithGolgiException:(GolgiException *)golgiException;
@end
@protocol GolDuinoButtonPressedRequestReceiver
- (void)buttonPressedWithResultSender:(id<GolDuinoButtonPressedResultSender>)resultSender andT:(NSInteger)t;
@end
@interface GolDuinoButtonPressedExceptionBundle: NSObject
{
    GolgiException * golgiException;
}
@property GolgiException * golgiException;
@end

//
// buttonReleased
//
@protocol GolDuinoButtonReleasedResultSender
- (NSString *)getRequestSenderId;
- (void)success;
@end
@protocol GolDuinoButtonReleasedResultReceiver
- (void)success;
- (void)failureWithGolgiException:(GolgiException *)golgiException;
@end
@protocol GolDuinoButtonReleasedRequestReceiver
- (void)buttonReleasedWithResultSender:(id<GolDuinoButtonReleasedResultSender>)resultSender andT:(NSInteger)t;
@end
@interface GolDuinoButtonReleasedExceptionBundle: NSObject
{
    GolgiException * golgiException;
}
@property GolgiException * golgiException;
@end

//
// setPotValue
//
@protocol GolDuinoSetPotValueResultSender
- (NSString *)getRequestSenderId;
- (void)success;
@end
@protocol GolDuinoSetPotValueResultReceiver
- (void)success;
- (void)failureWithGolgiException:(GolgiException *)golgiException;
@end
@protocol GolDuinoSetPotValueRequestReceiver
- (void)setPotValueWithResultSender:(id<GolDuinoSetPotValueResultSender>)resultSender andV:(NSInteger)v;
@end
@interface GolDuinoSetPotValueExceptionBundle: NSObject
{
    GolgiException * golgiException;
}
@property GolgiException * golgiException;
@end

//
// getPotValue
//
@protocol GolDuinoGetPotValueResultSender
- (NSString *)getRequestSenderId;
- (void)successWithResult:(PotValue *)result;
@end
@protocol GolDuinoGetPotValueResultReceiver
- (void)successWithResult:(PotValue *)result;
- (void)failureWithGolgiException:(GolgiException *)golgiException;
@end
@protocol GolDuinoGetPotValueRequestReceiver
- (void)getPotValueWithResultSender:(id<GolDuinoGetPotValueResultSender>)resultSender andPooky:(NSInteger)pooky;
@end
@interface GolDuinoGetPotValueExceptionBundle: NSObject
{
    GolgiException * golgiException;
}
@property GolgiException * golgiException;
@end

@interface GolDuinoSvc : NSObject
+ (void)sendSetPinUsingResultReceiver:(id<GolDuinoSetPinResultReceiver>)resultReceiver andDestination:(NSString *)_dst withSetting:(PinSetting *)setting;
+ (void)sendSetPinUsingResultReceiver:(id<GolDuinoSetPinResultReceiver>)resultReceiver withTransportOptions:(GolgiTransportOptions *)options andDestination:(NSString *)_dst withSetting:(PinSetting *)setting;
+ (void)sendSetPinUsingResultHandler:(void (^)(PinSetting *, GolDuinoSetPinExceptionBundle *))resultHandler andDestination:(NSString *)_dst withSetting:(PinSetting *)setting;
+ (void)sendSetPinUsingResultHandler:(void (^)(PinSetting *, GolDuinoSetPinExceptionBundle *))resultHandler withTransportOptions:(GolgiTransportOptions *)options andDestination:(NSString *)_dst withSetting:(PinSetting *)setting;
+ (void)httpSendSetPinUsingResultHandler:(void (^)(PinSetting *, GolDuinoSetPinExceptionBundle *))resultHandler andDestination:(NSString *)_dst withSetting:(PinSetting *)setting;
+ (void)sendSetPinUsingResultReceiver:(id<GolDuinoSetPinResultReceiver>)resultReceiver orResultHandler:(void (^)(PinSetting *, GolDuinoSetPinExceptionBundle *))resultHandler withTransportOptions:(GolgiTransportOptions *)options andDestination:(NSString *)_dst withSetting:(PinSetting *)setting;
+ (void)registerSetPinRequestReceiver:(id<GolDuinoSetPinRequestReceiver>)requestReceiver;
+ (void)registerSetPinRequestHandler:(void (^)(id<GolDuinoSetPinResultSender> resultSender, PinSetting * setting))requestHandler;

+ (void)sendSetIOUsingResultReceiver:(id<GolDuinoSetIOResultReceiver>)resultReceiver andDestination:(NSString *)_dst withIoState:(IOState *)ioState;
+ (void)sendSetIOUsingResultReceiver:(id<GolDuinoSetIOResultReceiver>)resultReceiver withTransportOptions:(GolgiTransportOptions *)options andDestination:(NSString *)_dst withIoState:(IOState *)ioState;
+ (void)sendSetIOUsingResultHandler:(void (^)(GolDuinoSetIOExceptionBundle *))resultHandler andDestination:(NSString *)_dst withIoState:(IOState *)ioState;
+ (void)sendSetIOUsingResultHandler:(void (^)(GolDuinoSetIOExceptionBundle *))resultHandler withTransportOptions:(GolgiTransportOptions *)options andDestination:(NSString *)_dst withIoState:(IOState *)ioState;
+ (void)httpSendSetIOUsingResultHandler:(void (^)(GolDuinoSetIOExceptionBundle *))resultHandler andDestination:(NSString *)_dst withIoState:(IOState *)ioState;
+ (void)sendSetIOUsingResultReceiver:(id<GolDuinoSetIOResultReceiver>)resultReceiver orResultHandler:(void (^)(GolDuinoSetIOExceptionBundle *))resultHandler withTransportOptions:(GolgiTransportOptions *)options andDestination:(NSString *)_dst withIoState:(IOState *)ioState;
+ (void)registerSetIORequestReceiver:(id<GolDuinoSetIORequestReceiver>)requestReceiver;
+ (void)registerSetIORequestHandler:(void (^)(id<GolDuinoSetIOResultSender> resultSender, IOState * ioState))requestHandler;

+ (void)sendButtonPressedUsingResultReceiver:(id<GolDuinoButtonPressedResultReceiver>)resultReceiver andDestination:(NSString *)_dst withT:(NSInteger)t;
+ (void)sendButtonPressedUsingResultReceiver:(id<GolDuinoButtonPressedResultReceiver>)resultReceiver withTransportOptions:(GolgiTransportOptions *)options andDestination:(NSString *)_dst withT:(NSInteger)t;
+ (void)sendButtonPressedUsingResultHandler:(void (^)(GolDuinoButtonPressedExceptionBundle *))resultHandler andDestination:(NSString *)_dst withT:(NSInteger)t;
+ (void)sendButtonPressedUsingResultHandler:(void (^)(GolDuinoButtonPressedExceptionBundle *))resultHandler withTransportOptions:(GolgiTransportOptions *)options andDestination:(NSString *)_dst withT:(NSInteger)t;
+ (void)httpSendButtonPressedUsingResultHandler:(void (^)(GolDuinoButtonPressedExceptionBundle *))resultHandler andDestination:(NSString *)_dst withT:(NSInteger)t;
+ (void)sendButtonPressedUsingResultReceiver:(id<GolDuinoButtonPressedResultReceiver>)resultReceiver orResultHandler:(void (^)(GolDuinoButtonPressedExceptionBundle *))resultHandler withTransportOptions:(GolgiTransportOptions *)options andDestination:(NSString *)_dst withT:(NSInteger)t;
+ (void)registerButtonPressedRequestReceiver:(id<GolDuinoButtonPressedRequestReceiver>)requestReceiver;
+ (void)registerButtonPressedRequestHandler:(void (^)(id<GolDuinoButtonPressedResultSender> resultSender, NSInteger t))requestHandler;

+ (void)sendButtonReleasedUsingResultReceiver:(id<GolDuinoButtonReleasedResultReceiver>)resultReceiver andDestination:(NSString *)_dst withT:(NSInteger)t;
+ (void)sendButtonReleasedUsingResultReceiver:(id<GolDuinoButtonReleasedResultReceiver>)resultReceiver withTransportOptions:(GolgiTransportOptions *)options andDestination:(NSString *)_dst withT:(NSInteger)t;
+ (void)sendButtonReleasedUsingResultHandler:(void (^)(GolDuinoButtonReleasedExceptionBundle *))resultHandler andDestination:(NSString *)_dst withT:(NSInteger)t;
+ (void)sendButtonReleasedUsingResultHandler:(void (^)(GolDuinoButtonReleasedExceptionBundle *))resultHandler withTransportOptions:(GolgiTransportOptions *)options andDestination:(NSString *)_dst withT:(NSInteger)t;
+ (void)httpSendButtonReleasedUsingResultHandler:(void (^)(GolDuinoButtonReleasedExceptionBundle *))resultHandler andDestination:(NSString *)_dst withT:(NSInteger)t;
+ (void)sendButtonReleasedUsingResultReceiver:(id<GolDuinoButtonReleasedResultReceiver>)resultReceiver orResultHandler:(void (^)(GolDuinoButtonReleasedExceptionBundle *))resultHandler withTransportOptions:(GolgiTransportOptions *)options andDestination:(NSString *)_dst withT:(NSInteger)t;
+ (void)registerButtonReleasedRequestReceiver:(id<GolDuinoButtonReleasedRequestReceiver>)requestReceiver;
+ (void)registerButtonReleasedRequestHandler:(void (^)(id<GolDuinoButtonReleasedResultSender> resultSender, NSInteger t))requestHandler;

+ (void)sendSetPotValueUsingResultReceiver:(id<GolDuinoSetPotValueResultReceiver>)resultReceiver andDestination:(NSString *)_dst withV:(NSInteger)v;
+ (void)sendSetPotValueUsingResultReceiver:(id<GolDuinoSetPotValueResultReceiver>)resultReceiver withTransportOptions:(GolgiTransportOptions *)options andDestination:(NSString *)_dst withV:(NSInteger)v;
+ (void)sendSetPotValueUsingResultHandler:(void (^)(GolDuinoSetPotValueExceptionBundle *))resultHandler andDestination:(NSString *)_dst withV:(NSInteger)v;
+ (void)sendSetPotValueUsingResultHandler:(void (^)(GolDuinoSetPotValueExceptionBundle *))resultHandler withTransportOptions:(GolgiTransportOptions *)options andDestination:(NSString *)_dst withV:(NSInteger)v;
+ (void)httpSendSetPotValueUsingResultHandler:(void (^)(GolDuinoSetPotValueExceptionBundle *))resultHandler andDestination:(NSString *)_dst withV:(NSInteger)v;
+ (void)sendSetPotValueUsingResultReceiver:(id<GolDuinoSetPotValueResultReceiver>)resultReceiver orResultHandler:(void (^)(GolDuinoSetPotValueExceptionBundle *))resultHandler withTransportOptions:(GolgiTransportOptions *)options andDestination:(NSString *)_dst withV:(NSInteger)v;
+ (void)registerSetPotValueRequestReceiver:(id<GolDuinoSetPotValueRequestReceiver>)requestReceiver;
+ (void)registerSetPotValueRequestHandler:(void (^)(id<GolDuinoSetPotValueResultSender> resultSender, NSInteger v))requestHandler;

+ (void)sendGetPotValueUsingResultReceiver:(id<GolDuinoGetPotValueResultReceiver>)resultReceiver andDestination:(NSString *)_dst withPooky:(NSInteger)pooky;
+ (void)sendGetPotValueUsingResultReceiver:(id<GolDuinoGetPotValueResultReceiver>)resultReceiver withTransportOptions:(GolgiTransportOptions *)options andDestination:(NSString *)_dst withPooky:(NSInteger)pooky;
+ (void)sendGetPotValueUsingResultHandler:(void (^)(PotValue *, GolDuinoGetPotValueExceptionBundle *))resultHandler andDestination:(NSString *)_dst withPooky:(NSInteger)pooky;
+ (void)sendGetPotValueUsingResultHandler:(void (^)(PotValue *, GolDuinoGetPotValueExceptionBundle *))resultHandler withTransportOptions:(GolgiTransportOptions *)options andDestination:(NSString *)_dst withPooky:(NSInteger)pooky;
+ (void)httpSendGetPotValueUsingResultHandler:(void (^)(PotValue *, GolDuinoGetPotValueExceptionBundle *))resultHandler andDestination:(NSString *)_dst withPooky:(NSInteger)pooky;
+ (void)sendGetPotValueUsingResultReceiver:(id<GolDuinoGetPotValueResultReceiver>)resultReceiver orResultHandler:(void (^)(PotValue *, GolDuinoGetPotValueExceptionBundle *))resultHandler withTransportOptions:(GolgiTransportOptions *)options andDestination:(NSString *)_dst withPooky:(NSInteger)pooky;
+ (void)registerGetPotValueRequestReceiver:(id<GolDuinoGetPotValueRequestReceiver>)requestReceiver;
+ (void)registerGetPotValueRequestHandler:(void (^)(id<GolDuinoGetPotValueResultSender> resultSender, NSInteger pooky))requestHandler;

@end
